server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartsumdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework: INFO
    com.smartsum: DEBUG
